### ISSUE TITLE
STP engine - when sensor recieves 504/503 errors while trying to consume data, incorrect token received along with the answer

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#694]
See following log, in case that sensor receives 503/504 error while trying to consume data, it gets some token along with the error, this token is from 20/03/18 and the sensor sets this token as last succeed infoton, that means that it skips all data till that token

```
2018-05-22 12:47:31,919 m-well-ppe-akka.actor.default-dispatcher-46] INFO  c.t.d.sparql.SparqlProcessorManager  - Got start request for job [job: oafull, config name:None, sensors: oafulloa-names, oafulloa-identifiers, oafulloa-organization, oafulloa-address, oafulloa-relationship, oafulloa-hierarchy, oafulloa-industry, oafulloa-phone] from the user
2018-05-22 12:47:35,351 m-well-ppe-akka.actor.default-dispatcher-46] INFO  c.t.d.sparql.SparqlProcessorManager  - starting job [job: oafull, config name:None, sensors: oafulloa-names, oafulloa-identifiers, oafulloa-organization, oafulloa-address, oafulloa-relationship, oafulloa-hierarchy, oafulloa-industry, oafulloa-phone]
2018-05-22 12:47:35,351 -well-ppe-akka.actor.default-dispatcher-116] INFO  rFillerActor [oafulloa-organization] - starting BufferFillerActor
2018-05-22 12:47:35,351 [scala-execution-context-global-27538]       INFO  c.Downloader [oafulloa-organization] - Got empty result. Waiting for 10 seconds before passing on the empty element.
2018-05-22 12:47:45,391 [scala-execution-context-global-280]         INFO  c.Downloader [oafulloa-organization] - Got empty result. Waiting for 10 seconds before passing on the empty element.
2018-05-22 12:47:55,422 [scala-execution-context-global-283]         INFO  c.Downloader [oafulloa-organization] - Got empty result. Waiting for 10 seconds before passing on the empty element.
2018-05-22 12:48:05,453 [scala-execution-context-global-11295]       INFO  c.Downloader [oafulloa-organization] - Got empty result. Waiting for 10 seconds before passing on the empty element.
2018-05-22 12:49:37,226 m-well-ppe-akka.actor.default-dispatcher-44] INFO  rFillerActor [oafulloa-organization] - received consume answer from host=NA status=504 Gateway Timeout token=ZAB6eJxVyzEOgzAMQNHLsGLHtEGUjaVjOYMFgSA1MUrcAcThKwYG1q_3yVZkm2f9ejQ1HTiyMqiXkCUm91OXMgwSDt1WB8V3_9C7a73q2iIKQx68C5xBp3hdJ8c-zRyXnXWRiJUhUxpbGrr1P-WgKgE entity=<html><body><h1>504 Gateway Time-out</h1>
2018-05-22 12:49:37,226 m-well-ppe-akka.actor.default-dispatcher-73] INFO  rFillerActor [oafulloa-organization] - error: Status is 504 Gateway Timeout consumer will perform retry in 10 seconds, token=ZAB6eJxVyzEOgzAMQNHLsGLHtEGUjaVjOYMFgSA1MUrcAcThKwYG1q_3yVZkm2f9ejQ1HTiyMqiXkCUm91OXMgwSDt1WB8V3_9C7a73q2iIKQx68C5xBp3hdJ8c-zRyXnXWRiJUhUxpbGrr1P-WgKgE
2018-05-22 12:49:37,226 m-well-ppe-akka.actor.default-dispatcher-73] ERROR rFillerActor [oafulloa-organization] - unexpected message: Failure(java.lang.Exception: Status is 504 Gateway Timeout)
2018-05-22 12:51:06,058 m-well-ppe-akka.actor.default-dispatcher-59] INFO  rFillerActor [oafulloa-organization] - received consume answer from host=c998fuucsnd17.int.thomsonreuters.com status=503 Service Unavailable token=TwB6eJwzNDUyNLUwMTc2tjSwqNFPSSxJ1CvJyM8tzs8rSi0tSS0q1kvOz60pqSxI1VPJqfIzdHO0yigpKbDS189P1CtOzkjNTSzWK0nLg-kCKdf3L0pPzMusSizJzM_TNzIwNNA1MNU1MEQRBwDkPyn- entity={"success":false,"error":"Failed to execute phase [fetch], [reduce] "}
2018-05-22 12:51:06,058 m-well-ppe-akka.actor.default-dispatcher-51] INFO  rFillerActor [oafulloa-organization] - error: Status is 503 Service Unavailable consumer will perform retry in 10 seconds, token=TwB6eJwzNDUyNLUwMTc2tjSwqNFPSSxJ1CvJyM8tzs8rSi0tSS0q1kvOz60pqSxI1VPJqfIzdHO0yigpKbDS189P1CtOzkjNTSzWK0nLg-kCKdf3L0pPzMusSizJzM_TNzIwNNA1MNU1MEQRBwDkPyn-
2018-05-22 12:51:06,058 m-well-ppe-akka.actor.default-dispatcher-51] ERROR rFillerActor [oafulloa-organization] - unexpected message: Failure(java.lang.Exception: Status is 503 Service Unavailable)
```

**Comment by nicklester** [comment]
This should be fixed with the transition to zstore. Please can this be tested once this is merged

**Comment by yanpom** [comment]
Not fixed

**Comment by nicklester** [comment]
It is possible recent merges will fix this. Please can you retest

**Comment by yanpom** [comment]
Still getting token on 503/504 errors. Token doesnt suppose to return with those tokens:

2018-07-17 06:51:26,066 -well-egl2-akka.actor.default-dispatcher-86] INFO  rFillerActor [oafulloa-organization] - error: Status is 504 Gateway Timeout consumer will perform retry in 10 seconds, token=lAB6eJxVyzEOgzAMQNHLsGLHkUIVNhZGegYL0gapiVHiDkUcvmJgYP16n5wl561_uK7zBy6sDBolVcklfDWUCrOkQ39bgOazTzQOfVTdekRhqHMMiSvoK1_XyfFZ3pzXnXWVjNaQaY1rDd36H-kUKgk

**Comment by YoniMataraso** [comment]
@yanpom Can you please verify.
